In [54]:
#Imprimindo uma string

In [55]:
s = 'olá mundo'

In [56]:
type(s)

str

In [57]:
len(s)

9

In [58]:
print(s)

olá mundo


In [59]:
#Concatenação de strings

In [60]:
print('Meu brasil' + 'Brasileiro')

Meu brasilBrasileiro


In [61]:
#Substitui uma substring por alguma outra coisa

In [62]:
s1 = s.replace('mundo', 'alou')

In [63]:
print(s1)

olá alou


In [64]:
#A string s começa com ola?

In [68]:
print(s.startswith("olá"))

True


In [69]:
#A string s termina com mundo?

In [73]:
print(s.endswith('alou'))

True


In [74]:
#Quantas ocorrências da palavra alou a string s1 possui?

In [76]:
print(s1.count('alou'))

1


In [77]:
#Como 'capitalizar': (transformar a primeira letra de uma string maiuscula' 

In [78]:
s2 = 'davi mentiu'

In [79]:
print(s2.capitalize())

Davi mentiu


In [80]:
#Como verificar se uma string só possui numeros

In [81]:
'1234'.isdigit()

True

In [82]:
'123abc'.isdigit()

False

In [83]:
s2.isdigit()

False

In [84]:
#Como verificar se uma string é alfanumerica (só possui letras e numeros)

In [85]:
s2.isalnum()

False

In [86]:
'123asd'.isalnum()

True

In [87]:
#Substrings em Phyton (slicing)

In [88]:
print(s2[0])

d


In [89]:
s3 = 'Paralelepipedo alegre'

In [90]:
print(s3[5])

e


In [91]:
print(s3[15])

a


In [92]:
print(s3[14])

In [93]:
print(s3[-1])

e


In [94]:
s3[0:3]

'Par'

In [95]:
s3[15:20]

'alegr'

In [96]:
print(s3[:3])

Par


In [97]:
print(s3[:])

Paralelepipedo alegre


In [98]:
print(s3[3:])

alelepipedo alegre


In [99]:
#Imprimir os caracteres nos indices pares e impares

In [100]:
print(s3[::2]) #par

Prllppd lge


In [101]:
print(s3[1::2]) #impar

aaeeieoaer


In [102]:
#A função print concatena strings com espaço entre elas

In [104]:
print('Louco', 'Abalo', 'Davi')

Louco Abalo Davi


In [105]:
#A função print converte números para string

In [106]:
print(1984, 'George Orwell')

1984 George Orwell


In [107]:
#As strings somadas com + são concatenas sem espaço entre elas

In [108]:
print('#' + "alou" + "mundão")

#aloumundão


In [109]:
#Forma mais avançada de formatação de string

In [113]:
frase = 'Um triangulo com base igual a {0} e altura igual a {1} possui area igual a {2}.' .format(3, 4, 12)
print(frase)

Um triangulo com base igual a 3 e altura igual a 4 possui area igual a 12.


In [114]:
frase2 = 'O homem de {0} metros está a {1} metros do chão.' .format(2, 5)
print(frase2)

O homem de 2 metros está a 5 metros do chão.


In [115]:
#Formatação de strings com f-strings

In [117]:
linguagem = 'phyton'
frase3 = f"programando em {linguagem}"
print(frase3)

programando em phyton


In [119]:
#Estruturas complexas em Phyton

In [120]:
primeira_lista = [1,2,3]

In [121]:
print(primeira_lista)

[1, 2, 3]


In [123]:
segunda_lista = ['Davi', 123, False]

In [124]:
print(segunda_lista)

['Davi', 123, False]


In [125]:
segunda_lista[0]

'Davi'

In [126]:
segunda_lista[-1]

False

In [128]:
segunda_lista.append('alou')

In [129]:
#O comando append adiciona valores a lista ao ultimo lugar
print(segunda_lista)

['Davi', 123, False, 'alou']


In [130]:
#Para remover elementos da lista usar o comando del
del segunda_lista[0]

In [131]:
print(segunda_lista)

[123, False, 'alou']


In [132]:
#Alteração de valores da lista
segunda_lista[0] = 'Davi'

In [133]:
print(segunda_lista)

['Davi', False, 'alou']


In [134]:
#Tuplas uma vez criada não se altera os elementos dela (igual a lista) a diferença na criação é o parenteses
primeira_tupla = ('davi', 1, 2.3, False)

In [135]:
print(primeira_tupla)

('davi', 1, 2.3, False)


In [136]:
type(primeira_tupla)

tuple

In [137]:
primeira_tupla[1]

1

In [138]:
primeira_tupla[3]

False

In [139]:
#Conjunto em phyton {utiliza as chaves} não tem elementos repetidos, e nao ordenado
conjunto = {1, 'davi', True}


In [140]:
print(conjunto)

{1, 'davi'}


In [143]:
conjunto.add('+ 1 elemento')

In [144]:
print(conjunto)

{1, 'davi', '+ 1 elemento'}


In [148]:
davi = conjunto.pop()
davi

'davi'

In [149]:
print(conjunto)

{'+ 1 elemento'}


In [150]:
#Dicionários em phyton

In [153]:
dicionario = {'nome':'davi', 'alou':3}

In [154]:
print(dicionario)

{'nome': 'davi', 'alou': 3}


In [155]:
type(dicionario)

dict

In [156]:
dicionario['nome']

'davi'

In [158]:
dicionario.values()

dict_values(['davi', 3])

In [159]:
dicionario.keys()

dict_keys(['nome', 'alou'])

In [160]:
dicionario.items()

dict_items([('nome', 'davi'), ('alou', 3)])

In [163]:
del dicionario['nome']

In [164]:
print(dicionario)

{'alou': 3}


In [165]:
#Transformando
conjunto = list(conjunto)

In [166]:
type(conjunto)

list

In [173]:
dicionario_davi = ([('df', 'Distrito Federal'), ('go', 'goaias')])

In [174]:
type(dicionario_davi)

list

In [175]:
dict(dicionario_davi)

{'df': 'Distrito Federal', 'go': 'goaias'}

In [1]:
#Concatenando listas com extend
x = [1,2,3]
x.extend([4,5,6])

In [2]:
print(x)

[1, 2, 3, 4, 5, 6]


In [3]:
#Controle de fluxo - estrutura de decisão

In [10]:
x = 0
for x in range(10):
    if x == 3:
        continue
        if x == 5:
            break
            print(x)


In [9]:
print(x)

9


In [13]:
y = 5
if y == 5:
    print('correto')


correto


In [14]:
y == 3

False

In [17]:
nome = 'Leon'
if nome == 'Leon':
    print('Acertou o nome')

Acertou o nome


In [19]:
x = 10
resto = x % 2
if resto == 1:
    print('o numero é par')
else:
    print('o numero é impar')

o numero é impar


In [20]:
x = 10
resto = x % 2
if resto == 0:
    print('o numero é par')
else:
    print('o numero é impar')

o numero é par


In [21]:
nota = 5
if nota >= 9:
    print('Tirou SS')
elif nota >= 7:
    print('Tirou MS')
elif nota >= 5:
    print('Tirou MM')
else:
    print('Tirou MI')


Tirou MM


In [22]:
nota = 7.5
if nota >= 9:
    print('Tirou SS')
elif nota >= 7:
    print('Tirou MS')
elif nota >= 5:
    print('Tirou MM')
else:
    print('Tirou MI')

Tirou MS


In [23]:
nota = 10
if nota >= 9:
    print('Tirou SS')
elif nota >= 7:
    print('Tirou MS')
elif nota >= 5:
    print('Tirou MM')
else:
    print('Tirou MI')

Tirou SS


In [24]:
#List comprehension:
#Fazendo com FOR

# - Caso 01: Dobrar o valor de um produto
# - Caso 02: Todos os produtos que custarem a cima de 1000 dolares, imposto de 50% sobre o valor total

In [56]:
lista_preços = [500, 1500, 2000, 100, 25]

In [57]:
#Caso 01
nova_lista_preços = []
for preço in lista_preços:
    nova_lista_preços.append(preços * 2)
print(nova_lista)

[[500, 1500, 2000, 100, 25, 500, 1500, 2000, 100, 25], [500, 1500, 2000, 100, 25, 500, 1500, 2000, 100, 25], [500, 1500, 2000, 100, 25, 500, 1500, 2000, 100, 25], [500, 1500, 2000, 100, 25, 500, 1500, 2000, 100, 25], [500, 1500, 2000, 100, 25, 500, 1500, 2000, 100, 25]]


In [58]:
#Fazendo com list comprehension:
#caso 01
nova_lista_preco2 = [preço * 2 for preço in lista_preços]


In [59]:
print(nova_lista_preco2)

[1000, 3000, 4000, 200, 50]


In [63]:
#Caso 02
imposto = []
for preço in lista_preços:
    if preço > 1000:
        imposto.append(preço * 0.5)
       

In [64]:
print(imposto)

[750.0, 1000.0]


In [66]:
#Fazendo com list comprehension:
#caso 02
imposto2 = [preço * 0.5 for preço in lista_preços if preço > 1000]
print(imposto2)

[750.0, 1000.0]


In [1]:
#Estrutura de repetição FOR
# for <estrutura de repetição>:
# <comandos a serem repetidos>

In [2]:
for i in range(7):
    print('gol da alemanha')
print('gol do brasil')    

gol da alemanha
gol da alemanha
gol da alemanha
gol da alemanha
gol da alemanha
gol da alemanha
gol da alemanha
gol do brasil


In [6]:
range(7)

range(0, 7)

In [7]:
list(range(7))

[0, 1, 2, 3, 4, 5, 6]

In [8]:
#Para problemas de elementos em lista:
# for elemento in lista:
# <comandos a serem repetidos>

In [10]:
abcd = [1,2,3,4,5]
for abcd in abcd:
    print('números')

números
números
números
números
números


In [19]:
alunos = ['davi', 'carol', 'gus', 'joao']

for aluno in alunos:
    print(aluno)

davi
carol
gus
joao


In [20]:
#Dicionário

In [21]:
dict_alunos = {'davi':5, 'maria':10}
for alunos in dict_alunos:
    print(alunos)

davi
maria


In [22]:
for aluno, nota in dict_alunos.items():
    print(f'O(a) aluno(a) {aluno} tirou nota {nota} na prova')

O(a) aluno(a) davi tirou nota 5 na prova
O(a) aluno(a) maria tirou nota 10 na prova


In [23]:
#Estrutura de repetição WHILE
#While <condição para repetição>:
#<comandos a serem repetidos>

In [24]:
cardapio = ['filé', 'strognof', 'frango', 'bolinho de arroz', 'camarão', 'batata frita']
item = cardapio.pop(0)

while item != 'camarão':
    print('Esse item não é camarão. Cade o Camarão!')
    item = cardapio.pop(0)

Esse item não é camarão. Cade o Camarão!
Esse item não é camarão. Cade o Camarão!
Esse item não é camarão. Cade o Camarão!
Esse item não é camarão. Cade o Camarão!


In [36]:
#Funções em python
#Estrutura:
# def nomedafuncao(parametro1, parametro2, ...):
   # corpodafuncao

In [40]:
def f(n):
    print('o valor da função é', n)

In [42]:
f(10)

o valor da função é 10


In [ ]:
def parabens():
    print('parabens parabens bens bens')

In [1]:
def somaQuadrados(a,b):
    somaQ = a**2 + b**2
    return somaQ

In [2]:
somaQuadrados(2,3)

13

In [3]:
#Expressões lambda - funções anonimas

In [10]:
preco = 500

def calcular_imposto(preco):
   return preco * 0.2

print(calcular_imposto(preco))

100.0


In [14]:
#Função lambda
calcular_imposto2 = lambda preco: preco * 0.2

print(calcular_imposto2(preco))

100.0


In [30]:
#Função lambda com lista de preços:

preco2 = [1, 10, 20, 30, 150]

calcular_imposto3 = list(map(lambda x: x*0.2, preco2))
print(calcular_imposto3)

[0.2, 2.0, 4.0, 6.0, 30.0]


# Parte 02-

### Bibliotecas e numpy:

## Bibliotecas:

In [34]:
### Exemplos:
import math
math.factorial(5)

import datetime
datetime.date.today()

datetime.date(2022, 7, 20)

In [37]:
## As funções possuem atributos:
datetime.date.today().day

20

In [40]:
datetime.date.isoformat(datetime.date.today()) ##Transformando a data

'2022-07-20'

In [43]:
## Importando apenas o modulo
from datetime import date
date.isoformat(date.today())

'2022-07-20'

## Numpy:

In [44]:
## Importação
import numpy as np

### O que é um array:


In [45]:
## ndarrays: N dimensões de arrays

#1-D array: possuí apenas uma dimensão, será chamado de vetor
#2-D array: possuí duas dimensões, será chamado de matriz
#3-D array ou mais: possui 3 dimensões ou mais, será chamado de tensor

In [47]:
# Criando um array
a = np.array([1,2,3,4,5])
print(a)
type(a)

[1 2 3 4 5]


numpy.ndarray

In [49]:
b = np.array([[1,2,3,4], [10,20,30,30]])
print(b)

[[ 1  2  3  4]
 [10 20 30 30]]


In [52]:
zero_array = np.zeros(shape = (5,3,6))
print(zero_array)

[[[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]]


In [54]:
##NP.empty
vazio = np.empty(3)  ##Fornece numeros aleatórios para três dimensões que nao estão vazias
print(vazio)

[1.39422063e-311 0.00000000e+000 4.94065646e-324]


In [59]:
##NP.arange

arr = np.arange(1,10)
print(arr)

[1 2 3 4 5 6 7 8 9]


In [61]:
##NP.linspace
array_linear = np.linspace(0, 100, num = 20, endpoint = False)
print(array_linear)

[ 0.  5. 10. 15. 20. 25. 30. 35. 40. 45. 50. 55. 60. 65. 70. 75. 80. 85.
 90. 95.]


In [63]:
array_linear = np.linspace(0, 100, num = 20, endpoint = True)
print(array_linear)  ## Com True ele considera o 100

[  0.           5.26315789  10.52631579  15.78947368  21.05263158
  26.31578947  31.57894737  36.84210526  42.10526316  47.36842105
  52.63157895  57.89473684  63.15789474  68.42105263  73.68421053
  78.94736842  84.21052632  89.47368421  94.73684211 100.        ]


In [66]:
## Desconbrindo o tamanho do array:
print(array_linear.shape)
print(array_linear.size)
print(array_linear.ndim)

(20,)
20
1


#### Transformando um vetor 1-D em uma matrix(2-D)

In [69]:
a = np.array([1,2,3])
print(a.shape)
print(a.ndim)

(3,)
1


In [71]:
a2 = np.array(a[np.newaxis, :])
print(a2.shape)
print(a2.ndim)
print(a2)

(1, 3)
2
[[1 2 3]]


#### Concatenando arrays

In [74]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,9,10])
c = np.concatenate((a,b))
d = np.concatenate((b,a))
print(c)
print(d)

[ 1  2  3  4  5  6  7  9 10]
[ 5  6  7  9 10  1  2  3  4]


#### Consultando itens de um array:

In [80]:
a = np.array([[1,2,3,4], [5,6,7,8], [20,40,50,60]])
print(a)
print('--------------------')
maior_8 = a[a%2==0]
print(maior_8)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [20 40 50 60]]
--------------------
[ 2  4  6  8 20 40 50 60]


#### Operações com arrays:

In [82]:
a = np.array([1,2,3,4])
print(a.sum())
print(a.min())
print(a.max())
print(a.mean())

10
1
4
2.5


#### Gerando amostras aleatorias:

In [83]:
from numpy.random import default_rng


In [86]:
rng = default_rng()
aleatorio = rng.integers(20, size= (2,4))
print(aleatorio)

[[10  5 11 15]
 [ 7  1 12  1]]


In [88]:
a = True
print(type(a))

<class 'bool'>
