# Exercicíos Python

## Bibliotecas e Numpy:

In [1]:
### 01- Para que serve o PIP no Python?
# O PIP serve para atualizar, as bibliotecas dentro do python, através dele você insere as bibliotecas e também realiza atualizações

In [3]:
### 02- Crie um array com 10 números no formato float. Converta-os para o formato inteiro.

# Importando a biblioteca numpy
import numpy as np

# Criando o array
array_1 = np.array([0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1.27])
print(type(array_1))


<class 'numpy.ndarray'>


In [10]:
#Convertendo para inteiro
import numpy as np

array_1 = np.asarray(array_1, dtype = int)
print(array_1)

[0 0 0 0 0 0 0 0 0 1]


In [12]:
### 03- Converta o array abaixo para o formato booleano.
import numpy as np
a = np.array([[1,0,1],[1,1,1],[0,0,0]])
a.astype(bool)

array([[ True, False,  True],
       [ True,  True,  True],
       [False, False, False]])

In [16]:
### 04- Empilhe horizontalmente os arrays abaixo.
a = np.array([[10,20,15],[0,0,20]])
b = np.array([[15,7,3],[5,5,8]])
print('Vertical stacking:\n', np.vstack((a, b)))

Vertical stacking:
 [[10 20 15]
 [ 0  0 20]
 [15  7  3]
 [ 5  5  8]]


In [18]:
### 05- Empilhe verticalmente os arrays do exercício 15.
a = np.array([[10,20,15],[0,0,20]])
b = np.array([[15,7,3],[5,5,8]])
print('Horizontal stacking:\n', np.hstack((a, b)))


Horizontal stacking:
 [[10 20 15 15  7  3]
 [ 0  0 20  5  5  8]]


In [32]:
### 06- Gere uma lista de números inteiros que vão de 0 a 100, de 2 em 2, e, na sequência, converta essa lista em um array.
import numpy as np
a = list(range(0, 101, 2))
ab = np.asarray(a)
print(type(ab))
print(ab)
print(a)
print(type(a))

<class 'numpy.ndarray'>
[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100]
<class 'list'>


In [48]:
### 07- Gere uma lista de valores que vão de 5 a 10 de 0.5 em 0.5.
import numpy as np
lista_a = np.arange(5, 10.5, 0.5)
lista_a_trans = list(lista_a)

print(lista_a)
type(lista_a)
print(lista_a_trans)
type(lista_a_trans)

[ 5.   5.5  6.   6.5  7.   7.5  8.   8.5  9.   9.5 10. ]
[5.0, 5.5, 6.0, 6.5, 7.0, 7.5, 8.0, 8.5, 9.0, 9.5, 10.0]


list

In [ ]:
### 08- 